import type { Course, ValueProp } from './types';

export const COURSES: Course[] = [
  {
    id: 'ai-produktivitas',
    emoji: '\u{1F916}',
    title: 'AI Produktivitas',
    tagline: 'AI untuk Orang Awam, Langsung Bisa Dipakai',
    description: 'Kelas ini dirancang khusus untuk pemula yang belum pernah pakai AI sama sekali. Kamu akan belajar menggunakan tools AI populer untuk bantu kerja sehari-hari — bikin tulisan, bikin gambar, bantu presentasi, sampai riset sederhana. Semua diajarkan dengan bahasa yang gampang dipahami, tanpa istilah teknis yang ribet.',
    topics: [
      'Mengenal AI: apa itu, cara pakai, dan tools populer (ChatGPT, Gemini, Canva AI)',
      'Bikin konten tulisan: caption medsos, artikel, email dengan AI',
      'Bikin gambar dan desain dengan AI (Canva AI, Leonardo AI)',
      'Bantu pekerjaan kantor: presentasi, laporan, rangkuman otomatis',
      'Riset dan belajar pakai AI — cocok untuk tugas sekolah/kuliah',
      'Tips & trik biar hasil AI maksimal (prompt sederhana untuk pemula)',
    ],
    audience: ['Karyawan', 'Ibu Rumah Tangga', 'Mahasiswa', 'Pelaku UMKM'],
    outcomes: [
      'Mampu menggunakan AI untuk membantu pekerjaan sehari-hari',
      'Bisa bikin konten, gambar, dan desain pakai AI dalam hitungan menit',
      'Punya skill digital yang bikin kamu lebih produktif dan percaya diri',
    ],
    price: 'Rp 500.000',
    waText: 'Halo, saya tertarik konsultasi Kelas AI Produktivitas. Apakah cocok untuk pemula tanpa background teknis?',
    color: '#4ECDC4',
    colorBg: '#E8FAF8',
    iconBg: '#D4F5F0',
    duration: '2x Pertemuan Intensif',
    badge: 'Popular',
  },
  {
    id: 'meta-ads',
    emoji: '\u{1F4E3}',
    title: 'Meta Ads',
    tagline: 'Iklankan Produk Sendiri di FB & IG — Pakai Landing Page atau CTWA',
    description: 'Kelas ini fokus ke cara praktis beriklan di Facebook & Instagram untuk mempromosikan produk kamu sendiri. Mulai dari bikin landing page sederhana, setup iklan pakai Click to WhatsApp (CTWA), sampai optimasi biaya iklan. Cocok banget buat pemilik usaha yang mau jualan online tanpa ribet.',
    topics: [
      'Dasar-dasar Meta Ads & Business Suite untuk pemula',
      'Strategi iklan berdasarkan produk — bukan cuma teori',
      'Membuat landing page sederhana untuk iklan produk',
      'Click to WhatsApp Ads (CTWA) — langsung ke chat penjualan',
      'Riset target audiens yang cocok dengan produk kamu',
      'Optimasi budget: biaya iklan efisien, hasil maksimal',
    ],
    audience: ['Owner Bisnis', 'Pelaku UMKM', 'Marketer', 'Freelancer'],
    outcomes: [
      'Mampu membuat dan menjalankan iklan untuk produk sendiri',
      'Bisa menggunakan landing page dan CTWA untuk promosi',
      'Punya strategi iklan yang terukur dan budget-friendly',
    ],
    price: 'Rp 500.000',
    waText: 'Halo, saya mau konsultasi Kelas Meta Ads. Saya ingin jualan online — apakah program ini cocok?',
    color: '#FF6B6B',
    colorBg: '#FFF0F0',
    iconBg: '#FFE4E4',
    duration: '2x Pertemuan Intensif',
    badge: 'Best Seller',
  },
  {
    id: 'affiliate-marketing',
    emoji: '\u{1F4B0}',
    title: 'Affiliate Marketing',
    tagline: 'Affiliate Shopee + Video AI, Tembak 4 Platform Sekaligus',
    description: 'Kelas ini fokus ke affiliate marketing Shopee — program afiliasi terbesar di Indonesia. Kamu akan belajar cara milih produk laris, bikin video promosi pakai AI, lalu crossposting otomatis ke TikTok, YouTube, Instagram, dan Facebook. Cocok buat yang mau cari penghasilan tambahan tanpa modal besar.',
    topics: [
      'Daftar dan mulai affiliate Shopee — lengkap dari nol',
      'Cara memilih produk Shopee yang laris dan komisi besar',
      'Bikin video produk pakai AI — tanpa skill editing',
      'Crossposting konten ke TikTok, YouTube, IG, dan FB',
      'Tips biar video affiliate viral dan banyak klik',
      'Tracking komisi dan optimasi penghasilan bulanan',
    ],
    audience: ['Pemula', 'Ibu Rumah Tangga', 'Mahasiswa', 'Content Creator'],
    outcomes: [
      'Bisa langsung praktik affiliate Shopee dari HP sendiri',
      'Mampu bikin video promosi produk dengan AI',
      'Punya strategi crossposting ke 4 platform sekaligus',
    ],
    price: 'Rp 500.000',
    waText: 'Halo, saya tertarik konsultasi Kelas Affiliate Marketing. Gimana cara mulai tanpa modal besar?',
    color: '#45B7D1',
    colorBg: '#EEF9FC',
    iconBg: '#DCF4FA',
    duration: '2x Pertemuan Intensif',
    badge: 'New',
  },
  {
    id: 'ai-coding',
    emoji: '\u{1F4BB}',
    title: 'AI Coding',
    tagline: 'Bikin Aplikasi Tanpa Harus Hafal Kode',
    description: 'Kelas ini mengajarkan cara membuat aplikasi web dan mobile dengan bantuan AI coding assistant. Kamu tidak perlu hafal sintaks atau menjadi programmer senior — cukup pahami logika dasarnya, AI akan membantu menulis kodenya.',
    topics: [
      'Dasar logika pemrograman tanpa harus coding manual',
      'Menggunakan AI coding assistant (Cursor, Copilot, Claude)',
      'Membuat landing page dan website sederhana',
      'Membangun aplikasi web dengan data dinamis',
      'Integrasi API dan database',
      'Deploy dan publikasi aplikasi ke internet',
    ],
    audience: ['Pemula', 'Owner Bisnis', 'Product Manager', 'Designer'],
    outcomes: [
      'Mampu membuat dan deploy aplikasi web sendiri',
      'Bisa menggunakan AI coding assistant secara efektif',
      'Punya portofolio 3 proyek nyata',
    ],
    price: 'Rp 500.000',
    waText: 'Halo, saya mau konsultasi Kelas AI Coding. Apakah cocok untuk yang nol programming?',
    color: '#9B59B6',
    colorBg: '#F3ECF9',
    iconBg: '#EAD5F5',
    duration: '2x Pertemuan Intensif',
    badge: 'Trending',
  },
];

export const VALUE_PROPS: ValueProp[] = [
  {
    icon: '\u{1F4B5}',
    title: 'Harga Terjangkau',
    desc: 'Hanya Rp 500.000 per kelas. Investasi sekali, skill bertahan seumur hidup.',
    color: '#10B981',
    colorBg: '#E7F9F1',
  },
  {
    icon: '\u{1F558}',
    title: 'Jadwal Weekend',
    desc: '2x pertemuan intensif tiap Hari Minggu. Nggak ganggu kerja atau kuliah.',
    color: '#6366F1',
    colorBg: '#EEEDFD',
  },
  {
    icon: '\u{1F30D}',
    title: 'Online + Offline',
    desc: 'Bisa ikut dari mana aja via Zoom, atau tatap muka langsung di Jombang.',
    color: '#F59E0B',
    colorBg: '#FEF3C7',
  },
  {
    icon: '\u{1F528}',
    title: 'Praktik Langsung',
    desc: 'Wajib PR dan final project. Bukan teori doang — beneran praktik.',
    color: '#EF4444',
    colorBg: '#FEE2E2',
  },
  {
    icon: '\u{1F468}\u200D\u{1F3EB}',
    title: 'Pendampingan',
    desc: '1 bulan support setelah kelas selesai. Konsultasi bebas tanya kapan aja.',
    color: '#8B5CF6',
    colorBg: '#EDE9FE',
  },
  {
    icon: '\u{1F4AC}',
    title: 'Komunitas Eksklusif',
    desc: 'Akses grup Telegram khusus. Saling sharing sesama peserta + mentor.',
    color: '#06B6D4',
    colorBg: '#CFFAFE',
  },
];

export const WA_PHONE = '6285280000449';

export const PARTNER_NAMES = [
  'YPSMA Jombang',
  'Vilona AI',
  'BerkahKarya Digital',
  'Nirwana Residence',
  'Ma\'arif NU',
];

export const TESTIMONIALS = [
  {
    name: 'Ahmad Fauzi',
    role: 'Karyawan Swasta',
    before: 'Baru kenal AI, bingung mulai dari mana',
    after: 'Sekarang tugas kantor beres 3x lebih cepat',
    company: 'Karyawan',
    quote: 'Dulu mikir AI itu susah dan cuma buat orang IT. Ternyata gampang banget. Sekarang bikin laporan, presentasi, email — semua selesai dalam hitungan menit.',
  },
  {
    name: 'Siti Nurhaliza',
    role: 'Ibu Rumah Tangga',
    before: 'Nggak punya penghasilan sendiri',
    after: 'Komisi affiliate Rp 2-3 juta/bulan',
    company: 'Affiliate Marketer',
    quote: 'Modal HP doang, sekarang bisa dapat penghasilan sendiri dari affiliate marketing.',
  },
  {
    name: 'Rudi Hartono',
    role: 'Owner UMKM',
    before: 'Buang budget iklan tapi hasil nihil',
    after: 'ROAS 5x dalam 2 minggu pertama',
    company: 'Pengusaha',
    quote: 'Meta Ads bener-bener ngubah cara saya pasarkan produk. Sekarang tiap rupiah budget iklan terukur.',
  },
];
